### ISSUE TITLE
error ssl

### ISSUE THREAD

**Issue by BilagoNet** [taimast/AiogramTemplate#2]
{"ok":true,"result":{"url":"***.**.**.**:8443/webhook","has_custom_certificate":true,"pending_update_count":1,"last_error_date":1722760475,"last_error_message":"SSL error {error:0A000086:SSL routines::certificate verify failed}","max_connections":40,"ip_address":"***.**.**.**","allowed_updates":["message","callback_query","my_chat_member","chat_member","chat_join_request"]}}

openssl req -newkey rsa:2048 -sha256 -nodes -keyout private.key -x509 -days 3650 -out cert.pem

**Comment by taimast** [comment]
Please check if the path to the certificate in config.yml is correct and if the webhook settings are properly configured. If you're having trouble, don't worry—webhooks are not mandatory, and you can run the application without them.
